---
title: Zombie apocalypse survival map
hero_image: images/banner.png
description: Create and navigate a GPS map to help you survive the zombie apocalypse
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-1, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: html-css-javascript
hardware: ''
software: html-css-javascript
site_areas: projects
version: 4
last_tested: 2017-09-01
steps:
- title: Introduction
- title: What you will need
- title: Create a web page
- title: Obtain a Google Maps API key
  completion:
  - engaged
- title: Display the map
- title: Place a marker
- title: Mark where you click
- title: Choose your icon
- title: Log your locations
  completion:
  - internal
- title: 'Challenge: prepare for zombies'
